FROM node:10

# User data directory, contains flows, config and nodes.
RUN mkdir /data

# Create app directory
WORKDIR /usr/src/app


# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install --production
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

VOLUME ["/data"]

CMD [ "node", "src/index.js" ]
